# --------------------------------------------------------------------------
# 1. Prompt Configuration: 定义如何构造发送给模型的提示
# --------------------------------------------------------------------------
prompt_template:
  system_text: |
    你是一个专业的代码质量评估专家。请根据提供的代码内容，从代码质量、可读性、实用性等维度进行评分。
  
  prompt_text: |
    请对以下代码进行质量评估：

    {code_corpus_description_and_sample}

    请从以下维度评分（1-5分）：
    1. 代码质量：语法正确性、最佳实践
    2. 可读性：注释、命名规范、结构清晰度
    3. 实用性：功能完整性、实际应用价值

    请以JSON格式回复，包含以下字段：
    - score: 综合评分(1-5)
    - quality_tags: 质量标签列表
    - main_languages: 主要编程语言列表
    - recommended_use_case: 推荐使用场景

# --------------------------------------------------------------------------
# 3. Output Configuration: 定义期望的输出格式和验证规则
# --------------------------------------------------------------------------
output_config:
  require_json: true
  json_keys: ["score", "quality_tags", "main_languages", "recommended_use_case"]
  json_key_must_exists: ["score"]
  json_default_values:
    score: 3
    quality_tags: []
    main_languages: []
    recommended_use_case: "通用代码示例"
