# DeepSeek V3 Configuration (from existing response_config.yaml)

client_config:
  base_url: "http://api.openai.com/v1/"
  api_key: "EMPTY"
  timeout: 600
  max_retries: 3

chat_config:
  model: "deepseek-v3-inner"
  temperature: 0.7
  max_tokens: 4000
  stream: false

