# Qwen3-480B Model Configuration
# 通用 Qwen3-480B 模型配置

client_config:
  base_url: "http://qwen3-480b-0.t-skyinfer-fjing.svc.cluster.local"
  api_key: "EMPTY"
  timeout: 600
  max_retries: 3

chat_config:
  model: "qwen3-480b"
  temperature: 0.6  # 较低的温度适用于需要事实性、确定性输出的场景
  max_tokens: 512
  # top_p: 0.95  # 其他可以控制模型输出的参数
