# Qwen3-480B External Configuration
# SiliconFlow Console 外部访问地址

client_config:
  base_url: "https://console.siflow.cn/siflow/auriga/skyinfer/fjing/qwen3-480b-0/v1"
  api_key: "EMPTY"
  timeout: 180
  max_retries: 3

chat_config:
  model: "qwen3-480b"
  temperature: 0.7
  max_tokens: 4000
  stream: false

