# =============================================================================
# 分布式评分任务配置
# =============================================================================

task_name: "distributed_rating"
description: "大规模分布式评分任务"

# 数据配置
data:
  input_folder: "users/yzli/formatted_data/score-model_universal-corp-en_raw_clean_fuzzydedup_sample100w/CC-MAIN-2014-35"
  output_folder: "users/yzli/tagged_data/distributed-rating/{timestamp}_run_{run_index}"
  stat_folder: "./data/stats/distributed-rating"
  input_key: "content_truncate_32k"
  prompt_format_key: "text"

# 模型配置
model:
  config_path: "configs/models/dpsk-v3-0526.yaml"
  
# 提示词配置  
prompt:
  config_path: "configs/prompts/en_corpus_rating_v0.1.yaml"

# 并发配置
concurrency:
  max_concurrent_files: 1
  max_concurrent_requests: 512
  chunk_size: 1024
  parquet_save_interval: 1024

# 分布式配置
distributed:
  enabled: true
  world_size: 10
  num_runs: 3  # 多轮运行
  
# 调试配置
debug:
  enabled: false
  max_files: null
  max_items_per_file: null

# 重试配置
retry:
  enable_format_validation_retry: true
  max_retries: 3

# 其他配置
options:
  resume: true
  delete_existing: false
  
# 环境配置
environment:
  api_provider: "local"  # local, siliconflow
  timeout: 300

# 日志配置
logging:
  level: "INFO"
  batch_size: 1000
  progress_report_interval: 50
