# =============================================================================
# GitHub代码评分任务配置
# =============================================================================

task_name: "github_code_rating"
description: "GitHub代码质量评分任务"

# 数据配置
data:
  input_folder: "users/jianzhou/text/score_model/en/raw_clean_fuzzydedup_sample100w/CC-MAIN-2014-35/"
  output_folder: "users/yzli/tagged_data/github-code-rating/{timestamp}"
  stat_folder: "./data/stats/github-code-rating"
  input_key: "text"
  prompt_format_key: "code_corpus_description_and_sample"

# 预处理配置 (可选)
preprocess:
  enabled: false                    # 设为true启用预处理
  script_type: "github_raw_code"    # 预处理脚本类型
  
  # 输入输出路径（如果不设置，会使用data.input_folder）
  input_folder: "users/raw_data/github_raw_code"  
  output_folder: "users/formatted_data/github_preprocessed"
  
  # 预处理参数
  max_tokens: 32768         # 最大token数
  num_proc: 16              # 处理进程数 
  seed: 42                  # 随机种子
  num_files: -1             # 处理文件数量 (-1表示全部)
  
  # 如果使用universal脚本，可以配置以下参数：
  # source_name: "github_code"
  # file_pattern: "*.parquet"
  # field_mapping:
  #   text: "content"
  #   source: "repository_url"
  # filters:
  #   min_text_length: 50
  #   max_text_length: 100000
  #   required_fields: ["content"]
  #   blacklist_patterns: ["password", "secret", "key="]

# 模型配置
model:
  config_path: "configs/models/dpsk-v3-0526.yaml"
  
# 提示词配置  
prompt:
  config_path: "configs/prompts/code_corpus_rating_v0.3.yaml"

# 并发配置
concurrency:
  max_concurrent_files: 2
  max_concurrent_requests: 10
  chunk_size: 100
  parquet_save_interval: 200

# 分布式配置
distributed:
  enabled: false
  world_size: 1
  
# 调试配置
debug:
  enabled: false
  max_files: 2
  max_items_per_file: 10

# 重试配置
retry:
  enable_format_validation_retry: true
  max_retries: 3

# 其他配置
options:
  resume: true
  delete_existing: false

# 日志配置
logging:
  level: "INFO"
  batch_size: 100
  progress_report_interval: 10
