# =============================================================================
# Repomix打包效果质量评分任务配置
# =============================================================================

task_name: "repomix_quality_rating"
task_type: "data_scoring"  # 任务类型：数据评分
description: "评估Repomix工具对代码仓库的打包效果质量"

# 数据配置
data:
  input_folder: "./data/formatted/repomix-quality"  # 预处理后的数据（本地路径）
  output_folder: "./data/tagged/repomix-quality/{timestamp}"
  stat_folder: "./data/stats/repomix-quality"
  input_key: "content_truncate_32k"  # 使用截断后的内容
  prompt_format_key: "content_truncate_32k"

# 预处理配置 - 启用Repomix XML预处理
preprocess:
  enabled: true                              # 启用预处理
  script_type: "repo_xml"                    # 使用代码仓库XML/CXML预处理脚本
  
  # 原始数据路径
  input_folder: "/volume/pt-train/users/wzhang/wjj-workspace/issue2commit/data/repomix_output"
  # 预处理输出路径
  output_folder: "./data/formatted/repomix-quality"
  
  # 预处理参数
  max_tokens: 32768         # 最大token数
  num_proc: 32              # 降低进程数，避免内存压力
  seed: 42                  # 随机种子
  num_files: -1             # 处理所有文件（-1表示不限制）
  
  # 新增：分批写入和内存管理配置
  batch_size: 500           # 每500个XML文件写入一次，避免内存溢出
                            # 可根据内存情况调整：内存大调高，内存小调低
  
  # 指定处理的编程语言（可选，不指定则处理全部）
  # languages: ["Arduino"]  # 注释掉以处理所有语言

# 模型配置
model:
  config_path: "configs/models/qwen3-coder-480b.yaml"

  # config_path: "configs/models/dpsk-v3-pro.yaml"
  
# 提示词配置  
prompt:
  config_path: "configs/prompts/repo_packaging_quality_rating_v1.0.yaml"

# 环境配置
environment:
  config_path: "env/add_qwen3_480b_external.env"  # 指定Qwen3-480B外部API环境
  # config_path: "env/add_siliconflow_api.env"  # 指定SiliconFlow API环境
  tos_config_path: "env/add_tos_key.env"      # 单独的TOS配置
  timeout: 1200  # API超时时间（秒）

# 并发配置 - 针对512 RPM限制优化
concurrency:
  max_concurrent_files: 1   # 降低文件并发度，减少内存压力
  max_concurrent_requests: 64  # 严格控制在512 RPM以内 (20*3秒*60/60 ≈ 400 RPM)
  chunk_size: 32            # 降低批次大小，避免突发流量
  parquet_save_interval: 100

# 分布式配置
distributed:
  enabled: false
  world_size: 1
  
# 调试配置
debug:
  enabled: false            # 禁用调试模式，处理所有数据
  max_files: -1             # 处理所有文件
  max_items_per_file: -1    # 处理所有项目
  # enabled: true             # 启用调试模式
  # max_files: 5              # 只处理5个文件
  # max_items_per_file: 10    # 每个文件只处理10个项目

# 重试配置
retry:
  enable_format_validation_retry: true
  max_retries: 3

# 其他配置
options:
  preprocess_resume: true   # 预处理断点续传
  main_resume: true         # 主处理断点续传（支持跨时间戳目录）
  delete_existing: false    # 不删除已有文件，配合断点续传使用

# 日志配置
logging:
  level: "INFO"
  batch_size: 20
  progress_report_interval: 3
