# =============================================================================
# 响应生成配置 - OpenAI API客户端和聊天配置
# =============================================================================

# OpenAI客户端配置
client_config:
  base_url: "http://api.openai.com/v1/"
  api_key: "EMPTY"
  timeout: 600  # 请求超时时间（秒）
  max_retries: 3  # 最大重试次数

# 聊天配置
chat_config:
  model: "deepseek-v3"  # 模型名称
  temperature: 0.7  # 温度参数
  max_tokens: 4000  # 最大token数
  stream: false  # 是否使用流式输出

